#!/usr/bin/perl
###############################################################################
# Copyright (c) 2011 by bgvanbur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
###############################################################################
use strict;
use warnings;

if ( $#ARGV != 0 ) {
    &Help();
}

open( DIS, '<'.$ARGV[0] );
while ( my $line = <DIS> ) {
    # reformat each line so it can be assembled before updated by hand
    if ( $line =~ m/^(0x[0-9A-F]+):\s+((0x[0-9A-F]{4}\s+)+)(.*)$/ ) {
	my $label = $1;
	my $values = $2;
	my $dis = $4;
	$values =~ s/\s+$//g;
	chomp $dis;
	$values =~ s/\s+0x/,0x/g;
	$line = "\t;; $label:\n\t;; $dis\n\tdc.w $values\n";
    }
    # SNASM68K does not accept (x,y) and (x,y,z) formats
    # it accepts x(y) and x(y,z) though
    $line =~ s/([\s,])\((-?0x[0-9A-F]+),([^,\)]+)\)/$1$2($3)/g;
    $line =~ s/([\s,])\((-?0x[0-9A-F]+),([^,\)]+),([^,\)]+)\)/$1$2($3,$4)/g;
    print $line;
}
close DIS;

sub Help {
    die '
scd68kdcleanup <file>

[description]
  cleans up the output from 68kd (a 68000 disassembler) to make it quicker
  to work on the disassmbly

';
}
