#!/bin/sh
###############################################################################
# Copyright (c) 2011 by bgvanbur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
###############################################################################
# make an iso out of a sega cd in the cdrom
#   * only supports 1 track sega cds for now, haven't tried more complex ones
###############################################################################

dd if=/dev/cdrom of=cdrom.iso

#cdrdao read-cd --read-raw --datafile cdrom.bin --device ATAPI:0,0,0 --driver generic-mmc-raw cdrom.cue
