#!/usr/bin/perl
###############################################################################
# Copyright (c) 2011 by bgvanbur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
###############################################################################

use strict;
use warnings;

# TODO cheap and use isoinfo, make platform independent

if ( $#ARGV != 1 ) {
    &Help();
}

my $iso = $ARGV[0];
my $isoIndex = $ARGV[1];

my @found;

if ( open( PIPE, "isoinfo -l -i \"$iso\" |" ) ) {
    while ( my $line = <PIPE> ) {
	if ( $line =~ /^\S+\s+\S+\s+\S+\s+\S+\s+(\d+)\s+[^\[]+\[\s*(\d+)\s+0+\s*\]\s+(\S+)\s*$/ ) {
	    my $fileSize = $1;
	    my $fileStartSector = $2;
	    my $fileName = $3;
	    #print "$fileSize $fileStartSector $fileName\n";
	    my $fileStart = $fileStartSector * 0x800;
	    if ( $isoIndex >= $fileStart &&
		 $isoIndex < $fileStart + $fileSize ) {
		my $offset = $isoIndex - $fileStart;
		push @found, "$fileName:$offset";
	    }
	}
    }
}
close PIPE;

if ( $#found > 0 ) {
    print "file_found_in_multiple_files\n";
} elsif ( $#found < 0 ) {
    print "file_not_found\n";
} else {
    print $found[0]."\n";
}

sub Help {
    die '
scdisofilefromoffset [isofile] [isoindex]

[description]
  given an ISO and an byte index into the ISO, report the file name and file
  offset of where the file that is located at that byte index

';
}
