#!/usr/bin/perl
###############################################################################
# Copyright (c) 2011 by bgvanbur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
###############################################################################
# I used this to convert cram part of savestate file the more convient endian
###############################################################################

use strict;
use warnings;

if ( $#ARGV < 0 ) {
    &Help();
}

foreach my $file (@ARGV) {
    if ( open( FILE, $file ) ) {
	binmode FILE;

	my $result = '';
	my $buffer = '';

	while (1) {
	    read( FILE, $buffer, 2 );
	    if ( length($buffer) != 2 ) {
		last;
	    }
	    $result .= substr($buffer,1,1) . substr($buffer,0,1);
	}

	close FILE;

	if ( open( FILE, ">$file") ) {
	    print FILE $result;
	}
    }

    close FILE;
}

sub Help {
    die '
scdlittle2bigword <files>

[description]
  Convert from little endian words to big endian words.  Used to covert CRAM
  part of a savestate to a more convient endian.

';
}
