#!/usr/bin/perl
###############################################################################
# I used this to convert cram part of savestate file the more convient endian
###############################################################################

use strict;
use warnings;

if ( $#ARGV < 0 ) {
    &Help();
}

foreach my $file (@ARGV) {
    if ( open( FILE, $file ) ) {
	binmode FILE;

	my $result = '';
	my $buffer = '';

	while (1) {
	    read( FILE, $buffer, 2 );
	    if ( length($buffer) != 2 ) {
		last;
	    }
	    $result .= substr($buffer,1,1) . substr($buffer,0,1);
	}

	close FILE;

	if ( open( FILE, ">$file") ) {
	    print FILE $result;
	}
    }

    close FILE;
}

sub Help {
    die '
scdlittle2bigword <files>

[description]
  Convert from little endian words to big endian words.  Used to covert CRAM
  part of a savestate to a more convient endian.

';
}
