#!/usr/bin/perl
###############################################################################
# Copyright (c) 2011 by bgvanbur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
###############################################################################
# replace part of a binary file with the contents of another binary file
###############################################################################

use strict;
use warnings;

if ( $#ARGV != 2 ) {
    &Help();
}

my $updateFileName = $ARGV[0];
my $updateOffset = $ARGV[1];
my $replaceFileName = $ARGV[2];

my $replaceFileSize = -s $replaceFileName;

if ( $replaceFileSize <= 0 ) {
    exit;
}

# TODO only replace part of the file as needed when I wanted to replace
# the SCD fun part of the ISO
# $replaceFileSize = 0x8000;

open( REPLACE, "<$replaceFileName" ) or die "Cannot read $replaceFileName\n";

my $replaceFileData = '';
if ( read( REPLACE, $replaceFileData, $replaceFileSize ) != $replaceFileSize ) {
    die "Cannot read all of $replaceFileName\n";
}

close REPLACE;

open( UPDATE, "+<$updateFileName" ) or die "Cannot update $updateFileName\n";
seek( UPDATE, $updateOffset, 0 );

print UPDATE $replaceFileData;

close UPDATE;

sub Help {
    die '
scdupdatebinfile <updatefile> <updateoffset> <replacefile>

[description]
  Replace part of a <updatefile> with the contents from <replacefile> at byte
  position <updateoffset>.  Useful for overriding files in an ISO.

';
}
